name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.7.2
        with:
          docs-folder: docs/
          formats: |-
            epub
            pdf
          pre-build-command: 'pip install -e .'
          pip-requirements: 'requirements-all.txt'
          apt-packages: 'gcc'
